# Generated by Django 3.1 on 2020-08-06 08:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=300)),
                ('difficulty', models.CharField(choices=[('1.0', 'Facile - base'), ('2.0', 'Facile - avanzato'), ('3.0', 'Media - base'), ('4.0', 'Media - avanzata'), ('5.0', 'Difficile - base'), ('6.0', 'Difficile - avanzata')], default='1.0', max_length=30)),
                ('genre', models.CharField(choices=[('PC', 'Punta e clicca'), ('A', 'Avventura'), ('GM', 'Gioco matematico'), ('ST', 'Story-telling'), ('GV', 'Giochi vocali'), ('R', 'Racing'), ('A', 'Altro...')], default='A', max_length=30)),
                ('price', models.FloatField(default=20.0)),
                ('video', models.FileField(upload_to='video_lessons')),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(5), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Packet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=300)),
                ('difficulty', models.CharField(choices=[('1.0', 'Facile - base'), ('2.0', 'Facile - avanzato'), ('3.0', 'Media - base'), ('4.0', 'Media - avanzata'), ('5.0', 'Difficile - base'), ('6.0', 'Difficile - avanzata')], default='1.0', max_length=30)),
                ('price', models.FloatField(default=100.0)),
                ('lessons', models.ManyToManyField(to='lessons_management.Lesson')),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(5), to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=300)),
                ('difficulty', models.CharField(choices=[('1.0', 'Facile - base'), ('2.0', 'Facile - avanzato'), ('3.0', 'Media - base'), ('4.0', 'Media - avanzata'), ('5.0', 'Difficile - base'), ('6.0', 'Difficile - avanzata')], default='1.0', max_length=30)),
                ('price', models.FloatField(default=300.0)),
                ('packets', models.ManyToManyField(to='lessons_management.Packet')),
                ('user', models.ForeignKey(null=True, on_delete=models.SET(5), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
