# Generated by Django 3.1 on 2020-08-06 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.RemoveField(
            model_name='packet',
            name='price',
        ),
    ]
