# Generated by Django 3.1 on 2020-08-06 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons_management', '0002_auto_20200806_0837'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedLessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lessons_management.lesson')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
